server:
  port: 8090

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url: 
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: user-service #Nombre de la app
        uri: lb://USER-SERVICE #Nombre del servicio en eureka
        predicates:
          - Path=/users/** #Path del endpoint a partir de cual se va a enrutar
      - id: car-service
        uri: lb://CAR-SERVICE/cars #Esta uri funciona igual como la de USER-SERVICE pero tambien se puede agregar el endpoint(ej: /cars) o sacarlo
        predicates:
          - Path=/cars/**
