server:
  port: 8050
spring:
  cloud:
    config:
      server:
        git:
          default-label: hotfix #branch name
          uri: https://github.com/KaykiPrex/microservices
          search-paths: config-data
  application:
    name: config-server
